name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Lua 5.1
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: '5.1'

    - uses: leafo/gh-actions-luarocks@v4

    - name: Install Dependencies
      run: |
        luarocks install luasec
        luarocks install luafilesystem
        luarocks install luasocket
        luarocks install luacheck
        luarocks install lua-cjson
        luarocks install penlight
        luarocks install lua-resty-http
        luarocks install lua-resty-string

    - name: Lint Code with Luacheck
      run: |
        luacheck . --no-color --exclude-files ".*"

    - name: Find .rockspec File
      id: find_rockspec
      run: |
        rockspec_file=$(find . -name "*.rockspec" | head -n 1)
        echo "Found rockspec file: $rockspec_file"
        echo "::set-output name=rockspec_file::$rockspec_file"

    - name: Build LuaRocks Package
      run: |
        luarocks pack ${{ steps.find_rockspec.outputs.rockspec_file }}
        mkdir -p rocks
        mv *.rock rocks/

    - name: Upload Rock to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: resty-yubikey-auth-rock
        path: rocks/